//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhiDeltZips.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int PlayerID { get; set; }
        public string PlayerName { get; set; }
        public Nullable<int> Y2010Points { get; set; }
        public Nullable<int> Y2010Wins { get; set; }
        public Nullable<int> Y2010Losses { get; set; }
        public Nullable<int> Y2010Ties { get; set; }
        public Nullable<int> Y2010Trades { get; set; }
        public Nullable<int> Y2010Finish { get; set; }
        public Nullable<int> Y2011Points { get; set; }
        public Nullable<int> Y2011Wins { get; set; }
        public Nullable<int> Y2011Losses { get; set; }
        public Nullable<int> Y2011Ties { get; set; }
        public Nullable<int> Y2011Trades { get; set; }
        public Nullable<int> Y2011Finish { get; set; }
        public Nullable<int> Y2012Points { get; set; }
        public Nullable<int> Y2012Wins { get; set; }
        public Nullable<int> Y2012Losses { get; set; }
        public Nullable<int> Y2012Ties { get; set; }
        public Nullable<int> Y2012Trades { get; set; }
        public Nullable<int> Y2012Finish { get; set; }
        public Nullable<int> Y2013Points { get; set; }
        public Nullable<int> Y2013Wins { get; set; }
        public Nullable<int> Y2013Losses { get; set; }
        public Nullable<int> Y2013Ties { get; set; }
        public Nullable<int> Y2013Trades { get; set; }
        public Nullable<int> Y2013Finish { get; set; }
        public Nullable<int> Y2014Points { get; set; }
        public Nullable<int> Y2014Wins { get; set; }
        public Nullable<int> Y2014Losses { get; set; }
        public Nullable<int> Y2014Ties { get; set; }
        public Nullable<int> Y2014Trades { get; set; }
        public Nullable<int> Y2014Finish { get; set; }
        public Nullable<int> Y2015Points { get; set; }
        public Nullable<int> Y2015Wins { get; set; }
        public Nullable<int> Y2015Losses { get; set; }
        public Nullable<int> Y2015Ties { get; set; }
        public Nullable<int> Y2015Trades { get; set; }
        public Nullable<int> Y2015Finish { get; set; }
        public Nullable<int> Y2016Points { get; set; }
        public Nullable<int> Y2016Wins { get; set; }
        public Nullable<int> Y2016Losses { get; set; }
        public Nullable<int> Y2016Ties { get; set; }
        public Nullable<int> Y2016Trades { get; set; }
        public Nullable<int> Y2016Finish { get; set; }
        public Nullable<int> Y2017Points { get; set; }
        public Nullable<int> Y2017Wins { get; set; }
        public Nullable<int> Y2017Losses { get; set; }
        public Nullable<int> Y2017Ties { get; set; }
        public Nullable<int> Y2017Trades { get; set; }
        public Nullable<int> Y2017Finish { get; set; }
        public Nullable<int> Y2018Points { get; set; }
        public Nullable<int> Y2018Wins { get; set; }
        public Nullable<int> Y2018Losses { get; set; }
        public Nullable<int> Y2018Ties { get; set; }
        public Nullable<int> Y2018Trades { get; set; }
        public Nullable<int> Y2018Finish { get; set; }
    }
}
