//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhiDeltZips.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Season
    {
        public int SeasonID { get; set; }
        public string SeasonYear { get; set; }
        public string SeasonChamp { get; set; }
        public string SeasonRunnerUp { get; set; }
        public string SeasonRegChamp { get; set; }
        public string SeasonRegRunnerUp { get; set; }
        public int TotalPoints { get; set; }
        public int TotalTrades { get; set; }
    }
}
